	<div id="footer"> 
		<div class="about-project section group"> 
		    <h1 class="logo"><img src="{site_url}imgs/invert-logo.jpg" alt="Made by Hand" /></h1> 
		    <p>Made by Hand is a short film series celebrating the people who makes things by hand&nbsp;&#8212; sustainably, locally, and with a love for their craft. <a href="../about/">more</a></p>
	 	</div><!--.section--> 
	 	<div class="twitter-feed group"> 
		    <h2 class="follow-twitter"><a href="http://twitter.com/madebyhand"><img src="{site_url}imgs/ft-twitter.jpg" alt="Follow @madebyhand on Twitter"/></a></h2> 
		    <ol>
		    {twitter}
		    </ol>
	 	</div><!--.section--> 
	 	<div class="copyright">
	 		<a href="mailto:{contact_email}">Contact</a>
	 		<span>Copyright &copy; {current_time format="%Y"} Made By Hand.</span><span>All rights reserved.</span>
	 	</div><!--.copyright--> 
	</div><!--#footer-->

</body> 
</html> 